# Site settings
title: Senthil Rajasekaran
author:
  name: Senthil Rajasekaran
  email: sr79@rice.edu
description: "Senthil Rajasekaran's Personal Website"

# Build settings
remote_theme: jekyll/minima
